### ISSUE TITLE
Warn about unrecognised schema version / always print version number used

### ISSUE THREAD

**Issue by stevenday** [openownership/cove-bods#56]
I've been using the BODS data review tool to develop a sample mapping for Indonesian data. I inadvertently set up my code to output a bodsVersion of 0.2.0, rather than 0.2, which seems to have led the tool to default to validating it as 0.1. It took me a while to work out this was the reason for some other validation errors.

It would be nice if
a) an unrecognised version number was a warning (or maybe even an error?)
b) the tool told you what version number it was using/defaulting to, even if you didn't specify one

**Comment by kd-ods** [comment]
(@odscjames - I came into the repo to add this bug and saw that Steve spotted the same thing last month.)

I'd add to Steve's list above:

c) the tool defaulted to validating against the latest version of the schema.

**Comment by kd-ods** [comment]
See issue #68 - this bug does cause misunderstandings. I think I rescind my (c) suggestion above, in favour of a message like this which addresses Steve's points:

"No valid value for bodsVersion has been found in these statements. The statements are being validated against BODS v0.1."

**Comment by odscjames** [comment]
Yes, (c) I think has to go as it would get difficult. BODS v0.1 didn't have anything to say what version it was, so we have to assume anything that doesn't try to specify a version is 0.1

Also, it turns out that we do tell people the schema version but only if it is 0.2! This logic dates to before 0.2 was released, so that can now be removed and we just always show which version it is using. So that will make (B) very easy to do.

So just (a) to do - alert if version number is specified but it is not recognised.

**Comment by odscjames** [comment]
> "No valid value for bodsVersion has been found in these statements. The statements are being validated against BODS v0.1."

This is tricky because no value for bodsVersion is technically valid! I'm going to suggest a UI where:

* if nothing is specified for bodsVersion at all it just uses 0.1 and says it is using it, without making it look like an error
* if 0.2 is specified for bodsVersion it uses 0.2 and says it is using it, without making it look like an error
* if something is specified for bodsVersion that is not valid (0.2.0, 0.3) if uses the latest version and says so but makes it look like an error

**Comment by odscjames** [comment]
> if something is specified for bodsVersion that is not valid (0.2.0, 0.3) if uses the latest version and says so but makes it look like an error

And I'm explicitly saying "uses the latest version" and not "uses 0.1" because that seems more useful for the user - more chance the other errors shown on the page will be useful.

**Comment by odscjames** [comment]
Here is UI suggestions:

# When a dictionary is given as version, ie not a string

![BODSdict](https://user-images.githubusercontent.com/37832009/135098002-4d4c226e-ed25-492b-9319-0cdb24555bea.png)

# When a blank string is given as version

![BODSblank](https://user-images.githubusercontent.com/37832009/135098039-ee3c9d0d-0013-4ac8-880d-3b4d49d7a3a0.png)

# When a version that does not yet exist is used

![BODS0 999](https://user-images.githubusercontent.com/37832009/135098079-19afaef4-3645-4ba1-a881-154506bb634e.png)

# And finally when a patch version is used

![BODS0 2 0](https://user-images.githubusercontent.com/37832009/135098115-eceb606b-4e95-4dd9-b658-87af40ea45b7.png)

# Notes

Note the error is always shown twice, sometimes 3 times.

It's always shown in "Schema Version" at the top and "Additional Checks" section. Maybe this is good, because the user will be used to looking in that section and might miss the top error? Or should we hide it from "Additional Checks"?

And sometimes, there is a JSON Schema issue to and a 3rd warning appears in "Validation Errors"

**Comment by kd-ods** [comment]
Thanks, @odscjames - looks like all the cases are being well handled. As I mentioned on our call, I'm not too worried about bods version issues being flagged at the top and also in the 'Additional checks' section: the more warnings the better on sthg so critical imo.

**Some suggested wording for these 'Schema version' section error messages:**

The first statement of the submitted data has a BODS version of: [INVALID BODS VERSION]

This is not a valid BODS version.

All statements in the submitted data will therefore be validated against the latest version of BODS: [BODS latest].

**Comment by odscjames** [comment]
Deployed
